apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1 # always one nginx pod should run
  selector:
    matchLabels:
      app: nginx
  template: # Pod Template (nginx)
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: c1
        image: nginx
        ports:
        - containerPort: 80