apiVersion: v1          
kind: Pod               
metadata:               
  name: multi-pod
spec:                   
  containers:
  - name: c1
    image: nginx
    ports:
    - containerPort: 80
  - name: c2
    image: nginx
    ports:
    - containerPort: 80